### ISSUE TITLE
Lisp error: invalid specializer (ORDERED-CONTAINER-MIXIN ARRAY)

### ISSUE THREAD

**Issue by justineuro** [roswell/quicklisp#1]
While following the instructions for installing the `maxima-jupyter` kernel similar to that described in  [https://github.com/robert-dodier/maxima-jupyter](https://github.com/robert-dodier/maxima-jupyter/) (Method 2), a Lisp error occurred during the installation of `pzmq-20171019-git` (compilation of  files: `grovel.c` and `grovel.grovel-tmp.lisp`).  The error message was:

```
 In method definition for INSERT-SEQUENCE, found an invalid specializer (ORDERED-CONTAINER-MIXIN
                                                                         ARRAY)
```

`jupyter notebook` starts and the `maxima-jupyter` kernel is detected but no connection was attained.

Additional info:  
- OS: Debian 8 (Jessie) LTS (until 2020)
-  `maxima-sage` was used instead of `maxima` (latter was linked to former in `/usr/bin`)
- Please see attached file: [`001bug-maxima-jupyter-20180803.txt`](https://github.com/roswell/quicklisp/files/2256413/001bug-maxima-jupyter-20180803.txt) for more details

Thank you in advance for any help you can give in this regard.

**Comment by snmsts** [comment]
This is a repository just gathering files from quicklisp project... Is this right place to ask the question?
